<?php

namespace App\Bantuan;

class TesFileKu
{

    public static function dataGuru()
    {

        $murids = [
            [
                'nama' => 'Novanda Raffa Maulana',
                'no_induk' => '3163522850',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-11-06',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Muhammad andi deswanto',
                'no_induk' => '0073451808',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Trukan',
                'tanggal_lahir' => '2015-07-09',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Aulia Putri',
                'no_induk' => '3163522831',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-04-30',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Randi Irawan',
                'no_induk' => '3163522846',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Gunung Kidul',
                'tanggal_lahir' => '2015-09-06',
                'agama' => 'Islam',
                'alamat' => 'Sukomakmur Rt. 002 Rw. 001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Subekti Riswanto',
                'no_induk' => '3163522820',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-09-26',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Yoga Tri Mulyo',
                'no_induk' => '3163522862',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2015-09-12',
                'agama' => 'Islam',
                'alamat' => 'Blawong Rt.004 Rw. -, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Ria Safrida',
                'no_induk' => '3163522810',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Melati',
                'tanggal_lahir' => '2015-10-10',
                'agama' => 'Islam',
                'alamat' => 'Prum Indah Langit Rt. 01 Rw.004, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Wanda Nur Habibah',
                'no_induk' => '3163522802',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2015-08-31',
                'agama' => 'Islam',
                'alamat' => 'Brajan Rt. 04, Trimulyo, Jetis, Bantul',
            ],
            [
                'nama' => 'Welly Ropanda',
                'no_induk' => '3163522811',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Surakarta',
                'tanggal_lahir' => '2015-08-12',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Nanda Dwi triyanti',
                'no_induk' => '3163522807',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-10-08',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ], [
                'nama' => 'Sulistia',
                'no_induk' => '3163522817',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Imogiri',
                'tanggal_lahir' => '2015-12-12',
                'agama' => 'Islam',
                'alamat' => 'Segoroyoso Rt. 005, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Dwi Handayani',
                'no_induk' => '3163522801',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2015-10-31',
                'agama' => 'Islam',
                'alamat' => 'Perum Sriwangi Rt. 01, Rw. 003 Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Kiki Enggal Triasno',
                'no_induk' => '3163522006',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'KulonProgo',
                'tanggal_lahir' => '2015-04-04',
                'agama' => 'Islam',
                'alamat' => 'Segoroyoso Rt. 001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Naila Yuwandita',
                'no_induk' => '0073451100',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Lubuk Sepuh',
                'tanggal_lahir' => '2013-06-05',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 01 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Rini Andriani',
                'no_induk' => '0073451401',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-12-09',
                'agama' => 'Islam',
                'alamat' => 'Peleret  Rt. 003, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Ariani Putri Kasmini',
                'no_induk' => '00734511231',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2013-09-06',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Aliya Masitoh',
                'no_induk' => '0073451404',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-12-31',
                'agama' => 'Islam',
                'alamat' => 'Perum Indah Rt. 007 Rw. 001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Salendra',
                'no_induk' => '3163522310',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-07-06',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Muhammad Afashari',
                'no_induk' => '31635228113',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Lumajang',
                'tanggal_lahir' => '2013-11-12',
                'agama' => 'Islam',
                'alamat' => 'Melati Rt. 01 Rw- , Segoroyoso, Pleret',
            ], [
                'nama' => 'Nurul Larasati',
                'no_induk' => '0073451131',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Magelang',
                'tanggal_lahir' => '2013-01-01',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Indah Tri Rohmah',
                'no_induk' => '0073451818',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2012-12-12',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Muhammad Bagas Wiratama',
                'no_induk' => '0073451801',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-09-06',
                'agama' => 'Islam',
                'alamat' => 'Kerto Rt. 04 Rw. 007 Segoroyoso, Pleret',
            ],  [
                'nama' => 'Tri Hidayat',
                'no_induk' => 'Tri Hidayat',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-12-12',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02 Rw-, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Trisno Putra Praja',
                'no_induk' => '3163522003',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-10-06',
                'agama' => 'Islam',
                'alamat' => 'Brajan Rt. 01 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Eka Indah Sawitri',
                'no_induk' => '3163522861',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-09-12',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Panji Kurniawan',
                'no_induk' => '3163522809',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-07-02',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Hilal Nur Hidayat',
                'no_induk' => '3163522111',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-03-12',
                'agama' => 'Islam',
                'alamat' => 'Segoroyoson Rt. 04 Rw.001, Segoroyoso, Pleret',
            ], [
                'nama' => 'Tristan Anggara',
                'no_induk' => '3163522102',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-10-10',
                'agama' => 'Protestan',
                'alamat' => 'Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Bintang Andika',
                'no_induk' => '0073451804',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-06-01',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Maya Listiani',
                'no_induk' => '3163522002',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Batang',
                'tanggal_lahir' => '2013-06-12',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Mesi Sesrianti',
                'no_induk' => '0073451809',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-06-21',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Susi Lastuti',
                'no_induk' => '3163522001',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2013-03-12',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 01, Segoroyoso, Pleret',
            ], [
                'nama' => 'Muhmmad Akbar Ikhwansa',
                'no_induk' => '0012456731',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-12-31',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Wulan Melinda',
                'no_induk' => '0073451812',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-05-04',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Indah Ratmayanti',
                'no_induk' => '0073452603',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-01-01',
                'agama' => 'Islam',
                'alamat' => 'Melati Rt. 002 Rw.- , Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Ella Valma',
                'no_induk' => '0073451285',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-01-02',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Savira Claudia',
                'no_induk' => '00734511124',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2014-12-31',
                'agama' => 'Islam',
                'alamat' => 'Pogung Ulur Rt. 02 Rw.001, Segoroyoso, Pleret',
            ],  [
                'nama' => 'Muhammad Aziz',
                'no_induk' => '0073451829',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-02-02',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'M. Ruzman',
                'no_induk' => '0073451823',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2014-11-29',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Andi Rahman',
                'no_induk' => '0073451456',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2014-12-29',
                'agama' => 'Islam',
                'alamat' => 'Pogung Rt. 02, Segoroyoso, Pleret',
            ],    [
                'nama' => 'Dwi Handayani',
                'no_induk' => '0073451432',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2014-01-01',
                'agama' => 'Islam',
                'alamat' => 'Rogan Ilir Rt. 005 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Puji Astuti',
                'no_induk' => '0073451228',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2014-11-12',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Muhmmad Yusuf',
                'no_induk' => '0073451887',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2014-11-29',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 002 Rw- , Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Dani',
                'no_induk' => '0073451800',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2014-07-07',
                'agama' => 'Islam',
                'alamat' => 'Perum Indah Permata 2 Blok C Rt. 02 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Akbar Alamsyah',
                'no_induk' => '0073451831',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2014-08-03',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 01 Rw-, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Oki Saputra',
                'no_induk' => '00734511312',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2014-09-12',
                'agama' => 'Islam',
                'alamat' => 'Segoroyoso Rt. 002 Rw-, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Dewa Nyoman Albert',
                'no_induk' => '0073451769',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bali',
                'tanggal_lahir' => '2012-12-31',
                'agama' => 'Budha',
                'alamat' => 'Trukan Rt. 03 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Gery Prostasius',
                'no_induk' => '0073451021',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Gunung Kidul',
                'tanggal_lahir' => '2012-12-09',
                'agama' => 'Katolik',
                'alamat' => 'Bawongan Rt. 002 Rw.004, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Imam Yusuf Hamka',
                'no_induk' => '00734511002',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2011-12-30',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Mesi Indah saputri',
                'no_induk' => '00734512001',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2012-01-12',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 001, Segoroyoso, Pleret, Bantul',
            ], [
                'nama' => 'Yani Fitri Ningrum',
                'no_induk' => '00734511202',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2012-12-12',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 003, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Nafiq Haki',
                'no_induk' => '00734511203',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-09-30',
                'agama' => 'Islam',
                'alamat' => 'Perum Indah 3 Rt. 002 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Dewa Nyoman Albert',
                'no_induk' => '00734511125',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bali',
                'tanggal_lahir' => '2012-08-27',
                'agama' => 'Hindu',
                'alamat' => 'Perum Indah 2 Rt. 002, Segoroyoso, Plere',
            ],
            [
                'nama' => 'Aprizal Candra Saputra',
                'no_induk' => '0073451128',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Lumajang',
                'tanggal_lahir' => '2012-06-28',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Annisa Maharani',
                'no_induk' => '0073451221',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2012-03-21',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 001 Rw.4, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Nur Hadizah',
                'no_induk' => '00734511225',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2012-06-04',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 003, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Ika Dwi Sari',
                'no_induk' => '00734511230',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-06-16',
                'agama' => 'Islam',
                'alamat' => 'Komplek Siti Khadijah K2 Rt. 02 Rw-, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Reni Tri Agustina',
                'no_induk' => '0073451113',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Magelang',
                'tanggal_lahir' => '2012-12-31',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Hendita Nur Isnaini',
                'no_induk' => '0066026514',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2012-12-12',
                'agama' => 'Islam',
                'alamat' => 'Desa Krangan  Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Wahyu Agung Setiawan',
                'no_induk' => '0017547881',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2012-08-05',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 003 Rw- , Segoroyoso, Pleret',
            ],  [
                'nama' => 'Candra Deyinta Anggraini',
                'no_induk' => '0058267927',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-12-31',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Risma Devi Arianti',
                'no_induk' => '0047984135',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-10-30',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Afif Dewa Pratama',
                'no_induk' => '0073451500',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-12-31',
                'agama' => 'Islam',
                'alamat' => 'Jl. Imogiri km3 Rt. 01 Rw-, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Arya Dimas Satya',
                'no_induk' => '00734511199',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2011-12-12',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Sondi Tandya Pratama',
                'no_induk' => '0073451133',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-03-12',
                'agama' => 'Islam',
                'alamat' => 'Perum Indah Permata 2 Rt. 11 Rw.001, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Bintang Muhammad Wildan',
                'no_induk' => '0073451132',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2011-10-10',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 01 Rw.- , Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Rosa Indriani',
                'no_induk' => '0073451129',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-12-12',
                'agama' => 'Islam',
                'alamat' => 'Perum Indah 2 Rt. 02 Rw- , Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Anang Wardana',
                'no_induk' => '0073451110',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-10-05',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 01, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Riswanda Puja Sakti',
                'no_induk' => '0073451202',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-11-19',
                'agama' => 'Islam',
                'alamat' => 'Kronggahan Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Dandi Kristiyanto',
                'no_induk' => '00734511204',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-08-13',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],  [
                'nama' => 'Rahmat Hidayat',
                'no_induk' => '00734512011',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-09-12',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Ayuning Tyasih',
                'no_induk' => '0073451807',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2011-08-12',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Ratih Kurniawati',
                'no_induk' => '0073451300',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-12-12',
                'agama' => 'Islam',
                'alamat' => 'Segoroyoso Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Sandi Setiawan',
                'no_induk' => '0073451210',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-12-31',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Dona Rajab',
                'no_induk' => '0073451211',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-07-11',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            // Masukkan data array associative lainnya sesuai dengan kolom yang ingin dimasukkan.
            // ...
        ];

        return $murids;
    }
}
