<?php

namespace App\DataDummy;

use Illuminate\Support\Facades\Hash;

class CustomeSeeder
{

    public static function dataMurid()
    {

        $murids = [
            [
                'nama' => 'Novanda Raffa Maulana',
                'no_induk' => '3163522850',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-11-06',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Muhammad andi deswanto',
                'no_induk' => '0073451808',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Trukan',
                'tanggal_lahir' => '2015-07-09',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Aulia Putri',
                'no_induk' => '3163522831',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-04-30',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Randi Irawan',
                'no_induk' => '3163522846',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Gunung Kidul',
                'tanggal_lahir' => '2015-09-06',
                'agama' => 'Islam',
                'alamat' => 'Sukomakmur Rt. 002 Rw. 001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Subekti Riswanto',
                'no_induk' => '3163522820',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-09-26',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Yoga Tri Mulyo',
                'no_induk' => '3163522862',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2015-09-12',
                'agama' => 'Islam',
                'alamat' => 'Blawong Rt.004 Rw. -, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Ria Safrida',
                'no_induk' => '3163522810',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Melati',
                'tanggal_lahir' => '2015-10-10',
                'agama' => 'Islam',
                'alamat' => 'Prum Indah Langit Rt. 01 Rw.004, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Wanda Nur Habibah',
                'no_induk' => '3163522802',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2015-08-31',
                'agama' => 'Islam',
                'alamat' => 'Brajan Rt. 04, Trimulyo, Jetis, Bantul',
            ],
            [
                'nama' => 'Welly Ropanda',
                'no_induk' => '3163522811',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Surakarta',
                'tanggal_lahir' => '2015-08-12',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Nanda Dwi triyanti',
                'no_induk' => '3163522807',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-10-08',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ], [
                'nama' => 'Sulistia',
                'no_induk' => '3163522817',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Imogiri',
                'tanggal_lahir' => '2015-12-12',
                'agama' => 'Islam',
                'alamat' => 'Segoroyoso Rt. 005, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Dwi Handayani',
                'no_induk' => '3163522801',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2015-10-31',
                'agama' => 'Islam',
                'alamat' => 'Perum Sriwangi Rt. 01, Rw. 003 Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Kiki Enggal Triasno',
                'no_induk' => '3163522006',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'KulonProgo',
                'tanggal_lahir' => '2015-04-04',
                'agama' => 'Islam',
                'alamat' => 'Segoroyoso Rt. 001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Naila Yuwandita',
                'no_induk' => '0073451100',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Lubuk Sepuh',
                'tanggal_lahir' => '2013-06-05',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 01 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Rini Andriani',
                'no_induk' => '0073451401',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-12-09',
                'agama' => 'Islam',
                'alamat' => 'Peleret  Rt. 003, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Ariani Putri Kasmini',
                'no_induk' => '00734511231',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2013-09-06',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Aliya Masitoh',
                'no_induk' => '0073451404',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-12-31',
                'agama' => 'Islam',
                'alamat' => 'Perum Indah Rt. 007 Rw. 001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Salendra',
                'no_induk' => '3163522310',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-07-06',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Muhammad Afashari',
                'no_induk' => '31635228113',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Lumajang',
                'tanggal_lahir' => '2013-11-12',
                'agama' => 'Islam',
                'alamat' => 'Melati Rt. 01 Rw- , Segoroyoso, Pleret',
            ], [
                'nama' => 'Nurul Larasati',
                'no_induk' => '0074451131',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Magelang',
                'tanggal_lahir' => '2013-01-01',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Indah Tri Rohmah',
                'no_induk' => '0073451818',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2012-12-12',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Muhammad Bagas Wiratama',
                'no_induk' => '0073451801',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-09-06',
                'agama' => 'Islam',
                'alamat' => 'Kerto Rt. 04 Rw. 007 Segoroyoso, Pleret',
            ],  [
                'nama' => 'Tri Hidayat',
                'no_induk' => 'Tri Hidayat',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-12-12',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02 Rw-, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Trisno Putra Praja',
                'no_induk' => '3163522003',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-10-06',
                'agama' => 'Islam',
                'alamat' => 'Brajan Rt. 01 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Eka Indah Sawitri',
                'no_induk' => '3163522861',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-09-12',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Panji Kurniawan',
                'no_induk' => '3163522809',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-07-02',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Hilal Nur Hidayat',
                'no_induk' => '3163522111',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-03-12',
                'agama' => 'Islam',
                'alamat' => 'Segoroyoson Rt. 04 Rw.001, Segoroyoso, Pleret',
            ], [
                'nama' => 'Tristan Anggara',
                'no_induk' => '3163522102',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-10-10',
                'agama' => 'Protestan',
                'alamat' => 'Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Bintang Andika',
                'no_induk' => '0073451804',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2013-06-01',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Maya Listiani',
                'no_induk' => '3163522002',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Batang',
                'tanggal_lahir' => '2013-06-12',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 04, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Mesi Sesrianti',
                'no_induk' => '0073451809',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-06-21',
                'agama' => 'Islam',
                'alamat' => 'Desa Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Susi Lastuti',
                'no_induk' => '3163522001',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2013-03-12',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 01, Segoroyoso, Pleret',
            ], [
                'nama' => 'Muhmmad Akbar Ikhwansa',
                'no_induk' => '0012456731',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-12-31',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Wulan Melinda',
                'no_induk' => '0073451812',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2013-05-04',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Indah Ratmayanti',
                'no_induk' => '0073452603',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-01-01',
                'agama' => 'Islam',
                'alamat' => 'Melati Rt. 002 Rw.- , Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Ella Valma',
                'no_induk' => '0073451285',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-01-02',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Savira Claudia',
                'no_induk' => '00734511124',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2014-12-31',
                'agama' => 'Islam',
                'alamat' => 'Pogung Ulur Rt. 02 Rw.001, Segoroyoso, Pleret',
            ],  [
                'nama' => 'Muhammad Aziz',
                'no_induk' => '0073451829',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2015-02-02',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'M. Ruzman',
                'no_induk' => '0073451823',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2014-11-29',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Andi Rahman',
                'no_induk' => '0073451456',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2014-12-29',
                'agama' => 'Islam',
                'alamat' => 'Pogung Rt. 02, Segoroyoso, Pleret',
            ],    [
                'nama' => 'Dwi Handayani',
                'no_induk' => '0073451432',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2014-01-01',
                'agama' => 'Islam',
                'alamat' => 'Rogan Ilir Rt. 005 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Puji Astuti',
                'no_induk' => '0073451228',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2014-11-12',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Muhmmad Yusuf',
                'no_induk' => '0073451887',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2014-11-29',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 002 Rw- , Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Dani',
                'no_induk' => '0073451800',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2014-07-07',
                'agama' => 'Islam',
                'alamat' => 'Perum Indah Permata 2 Blok C Rt. 02 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Akbar Alamsyah',
                'no_induk' => '0073451831',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2014-08-03',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 01 Rw-, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Oki Saputra',
                'no_induk' => '00744511312',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2014-09-12',
                'agama' => 'Islam',
                'alamat' => 'Segoroyoso Rt. 002 Rw-, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Dewa Nyoman Albert',
                'no_induk' => '0073451769',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bali',
                'tanggal_lahir' => '2012-12-31',
                'agama' => 'Budha',
                'alamat' => 'Trukan Rt. 03 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Gery Prostasius',
                'no_induk' => '0073451021',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Gunung Kidul',
                'tanggal_lahir' => '2012-12-09',
                'agama' => 'Katolik',
                'alamat' => 'Bawongan Rt. 002 Rw.004, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Imam Yusuf Hamka',
                'no_induk' => '00734511002',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2011-12-30',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Mesi Indah saputri',
                'no_induk' => '00734512001',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2012-01-12',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 001, Segoroyoso, Pleret, Bantul',
            ], [
                'nama' => 'Yani Fitri Ningrum',
                'no_induk' => '00734511202',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2012-12-12',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 003, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Nafiq Haki',
                'no_induk' => '00734511203',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-09-30',
                'agama' => 'Islam',
                'alamat' => 'Perum Indah 3 Rt. 002 Rw.001, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Dewa Nyoman Albert',
                'no_induk' => '00734511125',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bali',
                'tanggal_lahir' => '2012-08-27',
                'agama' => 'Hindu',
                'alamat' => 'Perum Indah 2 Rt. 002, Segoroyoso, Plere',
            ],
            [
                'nama' => 'Aprizal Candra Saputra',
                'no_induk' => '0073451128',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Lumajang',
                'tanggal_lahir' => '2012-06-28',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Annisa Maharani',
                'no_induk' => '0073451221',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2012-03-21',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 001 Rw.4, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Nur Hadizah',
                'no_induk' => '00734511225',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2012-06-04',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 003, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Ika Dwi Sari',
                'no_induk' => '00734511230',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-06-16',
                'agama' => 'Islam',
                'alamat' => 'Komplek Siti Khadijah K2 Rt. 02 Rw-, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Reni Tri Agustina',
                'no_induk' => '0073451113',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Magelang',
                'tanggal_lahir' => '2012-12-31',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Hendita Nur Isnaini',
                'no_induk' => '0066026514',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2012-12-12',
                'agama' => 'Islam',
                'alamat' => 'Desa Krangan  Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Wahyu Agung Setiawan',
                'no_induk' => '0017547881',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2012-08-05',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 003 Rw- , Segoroyoso, Pleret',
            ],  [
                'nama' => 'Candra Deyinta Anggraini',
                'no_induk' => '0058267927',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-12-31',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Risma Devi Arianti',
                'no_induk' => '0047984135',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-10-30',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Afif Dewa Pratama',
                'no_induk' => '0073451500',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-12-31',
                'agama' => 'Islam',
                'alamat' => 'Jl. Imogiri km3 Rt. 01 Rw-, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Arya Dimas Satya',
                'no_induk' => '00734511199',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2011-12-12',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Sondi Tandya Pratama',
                'no_induk' => '0073451133',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-03-12',
                'agama' => 'Islam',
                'alamat' => 'Perum Indah Permata 2 Rt. 11 Rw.001, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Bintang Muhammad Wildan',
                'no_induk' => '0073451132',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2011-10-10',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 01 Rw.- , Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Rosa Indriani',
                'no_induk' => '0073452129',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-12-12',
                'agama' => 'Islam',
                'alamat' => 'Perum Indah 2 Rt. 02 Rw- , Segoroyoso, Pleret',
            ],
            [
                'nama' => 'Anang Wardana',
                'no_induk' => '0033451110',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-10-05',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 01, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Riswanda Puja Sakti',
                'no_induk' => '0073451202',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-11-19',
                'agama' => 'Islam',
                'alamat' => 'Kronggahan Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Dandi Kristiyanto',
                'no_induk' => '00734511204',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-08-13',
                'agama' => 'Islam',
                'alamat' => 'Trukan Rt. 02, Segoroyoso, Pleret',
            ],  [
                'nama' => 'Rahmat Hidayat',
                'no_induk' => '00734512011',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-09-12',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Ayuning Tyasih',
                'no_induk' => '0073451807',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2011-08-12',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Ratih Kurniawati',
                'no_induk' => '0073451300',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Segoroyoso',
                'tanggal_lahir' => '2011-12-12',
                'agama' => 'Islam',
                'alamat' => 'Segoroyoso Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Sandi Setiawan',
                'no_induk' => '0073451210',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-12-31',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Dona Rajab',
                'no_induk' => '0073451211',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Peleret',
                'tanggal_lahir' => '2011-07-11',
                'agama' => 'Islam',
                'alamat' => 'Peleret Rt. 02, Segoroyoso, Pleret, Bantul',
            ],
            [
                'nama' => 'Putra Utama',
                'no_induk' => '0073451101',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-05-10',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 123, Yogyakarta',
            ],
            [
                'nama' => 'Putri Utami',
                'no_induk' => '0073451102',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-05-10',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 124, Yogyakarta',
            ],
            [
                'nama' => 'Rizki Pratama',
                'no_induk' => '0073451103',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-05-12',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 125, Yogyakarta',
            ],
            [
                'nama' => 'Rizka Pratiwi',
                'no_induk' => '0073451104',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-05-12',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 126, Yogyakarta',
            ],

            [
                'nama' => 'Budi Santoso',
                'no_induk' => '0073451105',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-06-15',
                'agama' => 'Islam',
                'alamat' => 'Jl. Kaliurang No. 11, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Siti Rahayu',
                'no_induk' => '0073451106',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bantul',
                'tanggal_lahir' => '2012-07-20',
                'agama' => 'Islam',
                'alamat' => 'Jl. Parangtritis No. 15, Bantul, Yogyakarta',
            ],
            [
                'nama' => 'Ari Setiawan',
                'no_induk' => '0073451107',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-08-05',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 127, Yogyakarta',
            ],
            [
                'nama' => 'Dewi Lestari',
                'no_induk' => '0073451108',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-08-05',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 128, Yogyakarta',
            ],
            [
                'nama' => 'Fajar Pratama',
                'no_induk' => '0073451109',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-09-20',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 129, Yogyakarta',
            ],
            [
                'nama' => 'Wulan Kusuma',
                'no_induk' => '0073451110',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-09-20',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 130, Yogyakarta',
            ],
            [
                'nama' => 'Ahmad Satria',
                'no_induk' => '0073451111',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-10-12',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 131, Yogyakarta',
            ],
            [
                'nama' => 'Anisa Putri',
                'no_induk' => '0071451112',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-10-12',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 132, Yogyakarta',
            ],  [
                'nama' => 'Bambang Sudarmanto',
                'no_induk' => '0033451111',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-10-05',
                'agama' => 'Islam',
                'alamat' => 'Jl. Kaliurang No. 25, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Ani Rahmawati',
                'no_induk' => '0073451112',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-11-10',
                'agama' => 'Islam',
                'alamat' => 'Jl. Tugu No. 7, Yogyakarta',
            ],
            [
                'nama' => 'Fajar Prasetyo',
                'no_induk' => '0079451113',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-11-12',
                'agama' => 'Islam',
                'alamat' => 'Jl. Magelang No. 18, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Rini Suryani',
                'no_induk' => '0073451114',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-12-15',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 190, Yogyakarta',
            ],
            [
                'nama' => 'Rudi Hermawan',
                'no_induk' => '0073451115',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2012-06-20',
                'agama' => 'Islam',
                'alamat' => 'Jl. Sudirman No. 50, Jakarta',
            ],
            [
                'nama' => 'Indra Wijaya',
                'no_induk' => '0073451116',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2012-07-25',
                'agama' => 'Islam',
                'alamat' => 'Jl. Riau No. 12, Bandung',
            ],
            [
                'nama' => 'Dewi Lestari',
                'no_induk' => '0073451123',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-12-15',
                'agama' => 'Islam',
                'alamat' => 'Jl. Parangtritis No. 32, Bantul, Yogyakarta',
            ],
            [
                'nama' => 'Iwan Susanto',
                'no_induk' => '0073451124',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-09-18',
                'agama' => 'Islam',
                'alamat' => 'Jl. Kaliurang No. 14, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Ayu Rahmawati',
                'no_induk' => '0073451125',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-10-13',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 68, Yogyakarta',
            ],
            [
                'nama' => 'Dicky Santoso',
                'no_induk' => '0073451126',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-11-25',
                'agama' => 'Islam',
                'alamat' => 'Jl. Magelang No. 54, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Tuti Maryati',
                'no_induk' => '0073451127',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2012-07-20',
                'agama' => 'Islam',
                'alamat' => 'Jl. Riau No. 22, Bandung',
            ],
            [
                'nama' => 'Doni Hermawan',
                'no_induk' => '0074451130',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2012-06-22',
                'agama' => 'Islam',
                'alamat' => 'Jl. Sudirman No. 64, Jakarta',
            ],
            [
                'nama' => 'Andi Kusuma',
                'no_induk' => '0073451129',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-08-10',
                'agama' => 'Islam',
                'alamat' => 'Jl. Parangtritis No. 28, Bantul, Yogyakarta',
            ],
            [
                'nama' => 'Siti Indah',
                'no_induk' => '0073451130',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-09-22',
                'agama' => 'Islam',
                'alamat' => 'Jl. Kaliurang No. 17, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Rizki Perdana',
                'no_induk' => '0073451131',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-10-20',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 71, Yogyakarta',
            ],
            [
                'nama' => 'Putri Anggraini',
                'no_induk' => '0074451132',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-11-14',
                'agama' => 'Islam',
                'alamat' => 'Jl. Magelang No. 52, Sleman, Yogyakarta',
            ],

            [
                'nama' => 'Eka Purnama',
                'no_induk' => '0074451133',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2012-06-11',
                'agama' => 'Islam',
                'alamat' => 'Jl. Raya Darmo No. 88, Surabaya',
            ],
            [
                'nama' => 'Wulan Sari',
                'no_induk' => '0073451134',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2012-07-18',
                'agama' => 'Islam',
                'alamat' => 'Jl. Sisingamangaraja No. 7, Semarang',
            ], [
                'nama' => 'Rina Permata',
                'no_induk' => '0073451135',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-08-15',
                'agama' => 'Islam',
                'alamat' => 'Jl. Parangtritis No. 28, Bantul, Yogyakarta',
            ],
            [
                'nama' => 'Irfan Firdaus',
                'no_induk' => '0073451136',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-09-28',
                'agama' => 'Islam',
                'alamat' => 'Jl. Kaliurang No. 17, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Rini Permatasari',
                'no_induk' => '0073451137',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-10-25',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 71, Yogyakarta',
            ],
            [
                'nama' => 'Fandi Pratama',
                'no_induk' => '0073451138',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-11-18',
                'agama' => 'Islam',
                'alamat' => 'Jl. Magelang No. 52, Sleman, Yogyakarta',
            ],
            // Data siswa dari wilayah lain
            [
                'nama' => 'Dewi Anggraeni',
                'no_induk' => '0073451139',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2012-06-20',
                'agama' => 'Islam',
                'alamat' => 'Jl. Raya Darmo No. 88, Surabaya',
            ],
            [
                'nama' => 'Wahyu Sari',
                'no_induk' => '0073451140',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2012-07-25',
                'agama' => 'Islam',
                'alamat' => 'Jl. Sisingamangaraja No. 7, Semarang',
            ],  [
                'nama' => 'Yuni Wulandari',
                'no_induk' => '0073451157',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-07-12',
                'agama' => 'Islam',
                'alamat' => 'Jl. Kusumanegara No. 25, Yogyakarta',
            ],
            [
                'nama' => 'Bagus Pratama',
                'no_induk' => '0073451158',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-09-28',
                'agama' => 'Islam',
                'alamat' => 'Jl. Pakem No. 32, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Sari Indah',
                'no_induk' => '0073451159',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-06-18',
                'agama' => 'Islam',
                'alamat' => 'Jl. Solo No. 12, Yogyakarta',
            ],
            [
                'nama' => 'Eko Prasetyo',
                'no_induk' => '0073451160',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-08-20',
                'agama' => 'Islam',
                'alamat' => 'Jl. Imogiri No. 10, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Fitri Rahayu',
                'no_induk' => '0073451161',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-10-15',
                'agama' => 'Islam',
                'alamat' => 'Jl. Gejayan No. 35, Yogyakarta',
            ],
            [
                'nama' => 'Indra Kusuma',
                'no_induk' => '0073451162',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-11-22',
                'agama' => 'Islam',
                'alamat' => 'Jl. Magelang No. 42, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Dewi Fitriani',
                'no_induk' => '0073451163',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-07-30',
                'agama' => 'Islam',
                'alamat' => 'Jl. Kaliurang No. 18, Yogyakarta',
            ],
            [
                'nama' => 'Eko Prasetyo',
                'no_induk' => '0073451164',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-09-28',
                'agama' => 'Islam',
                'alamat' => 'Jl. Pakem No. 32, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Dina Fitriani',
                'no_induk' => '0073451170',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-11-22',
                'agama' => 'Islam',
                'alamat' => 'Jl. Sleman No. 40, Sleman, Yogyakarta',
            ],
            [
                'nama' => 'Joko Suryo',
                'no_induk' => '0073451171',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2012-07-30',
                'agama' => 'Islam',
                'alamat' => 'Jl. Imogiri No. 48, Yogyakarta',
            ],
            [
                'nama' => 'Siti Rahayu',
                'no_induk' => '0073451168',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '2012-07-18',
                'agama' => 'Islam',
                'alamat' => 'Jl. Magelang No. 30, Sleman, Yogyakarta',
            ],
        ];

        return $murids;
    }

    public static function dataGuru()
    {
        $guru = [
            [
                'nip' => '198509182022212025',
                'nama' => 'Atika Susi Chomaryati,S. Pd.SD',
                'jenis_kelamin' => 'P',
                'username' => 'atika',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Jaranan, Rt. 01, Panggungharjo, Sewon, Bantul',
                'telp' => '082231124780',
            ],
            [
                'nip' => '197010311993122001',
                'nama' => 'Eny Karuniawati,S. Pd',
                'jenis_kelamin' => 'P',
                'username' => 'eny',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Perum Berlian Indah A7 Rt.22 Rw. 6 Pandeyan, Umbulharjo, Yk',
                'telp' => '085326760956',
            ],
            [
                'nip' => '196304171984052001',
                'nama' => 'Prini, S.Pd',
                'jenis_kelamin' => 'P',
                'username' => 'prini',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Jati Rt. 6 Rw.- Wonokromo, Pleret Bantul',
                'telp' => '081234212473',
            ],
            [
                'nip' => '198908132019022001',
                'nama' => 'Ainun Ainiyah, S.Pd',
                'jenis_kelamin' => 'P',
                'username' => 'ainun',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Kerto Rt. 2 Rw- Peleret, Bantul',
                'telp' => '082234890952',
            ],
            [
                'nip' => '199702102020122005',
                'nama' => 'Nurul Fitri Hidayati, S.Pd',
                'jenis_kelamin' => 'P',
                'username' => 'nurul',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Jln. Imogiri Timur Km 10 Wonokromo2, Peleret, Bantul',
                'telp' => '081234212473',
            ],
            [
                'nip' => '199309042020122013',
                'nama' => 'Dita Ayuning Tyas, S.Pd',
                'jenis_kelamin' => 'P',
                'username' => 'dita',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Nepi Pedukuhan VII Rt. 031 Rw. 014, Brosot, Galur, Kulonprogo',
                'telp' => '082126760910',
            ],
            [
                'nip' => '199304172022212018',
                'nama' => 'Zeti Sulistiyowati, M.Pd',
                'jenis_kelamin' => 'P',
                'username' => 'zeti',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Blowong 2 Rt. 4 Rw - Trimulyo, Jetis, Bantul',
                'telp' => '082231124780',
            ],
            [
                'nip' => '5152758660300013',
                'nama' => 'Anik Susanti, S. Pd',
                'jenis_kelamin' => 'P',
                'username' => 'anik',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Brajan Rt. 01 Rw.5, Peleret, Bantul',
                'telp' => '08123421246781',
            ],
            [
                'nip' => '7437777678230002',
                'nama' => 'Ari Hidayaturrohmah, S.Ag',
                'jenis_kelamin' => 'L',
                'username' => 'ari',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Betisan Punggur  Rt. 01 Rw.5, Peleret, Bantul',
                'telp' => '0853267601019',
            ],
            [
                'nip' => '7252768669130133',
                'nama' => 'Septiani, S.Pd',
                'jenis_kelamin' => 'P',
                'username' => 'septiani',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Trukan Rt. 002 Rw.- , Peleret, Bantul',
                'telp' => '0812342897476',
            ],
            [
                'nip' => '1936743647200022',
                'nama' => 'Suhardi, S.Pd',
                'jenis_kelamin' => 'L',
                'username' => 'suhardi',
                'password' => Hash::make('qweqwe123'),
                'alamat' => 'Tobok Ijo, Rt.04 Rw.01, Peleret, Bantul',
                'telp' => '085267896043',
            ],
        ];
        return $guru;
    }
}
